# Header
menu:
  首页: /
  归档: /archives
  关于: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- time
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: false
favicon: /favicon32.ico
twitter:
google_plus:
fb_admins:
fb_app_id:


# Toc
toc:
  article: true 
  aside: true 

# Author information
author:
  github: navyxie

# duoshuo
duoshuo_shortname: navyxie

# ibruce 不算子计数（http://service.ibruce.info/）
ibruce_counter: true

# baidu tongji
baidu_tongji: true