# Header
menu:
  首页: /
  归档: /archives
  分类: /categories
  标签: /tags
  关于: /about
  Github: https://github.com/navyxie

rss: /atom.xml

# Content
excerpt_link: 阅读全文 >
fancybox: true

# Sidebar
sidebar: right
widgets:
- time
#- category
#- tag
#- archive
- recent_posts
- tagcloud
- duoshuo
# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: false
favicon: /favicon32.ico
twitter:
google_plus:
fb_admins:
fb_app_id:


# Toc
toc:
  article: true 
  aside: true 

# Author information
author:
  github: navyxie

# duoshuo
duoshuo_shortname: navyxie

# ibruce 不算子计数（http://service.ibruce.info/）
ibruce_counter: true

# baidu tongji
baidu_tongji: true

# Enable baidu push so that the blog will push the url to baidu automatically which is very helpful for SEO
baidu_push: true

#swiftype search : https://swiftype.com/
swift_search: true